### ISSUE TITLE
GB Photo app shows last photo as deleted

### ISSUE THREAD

**Issue by nortakales** [EstebanFuentealba/MALVEKE-Flipper-Zero#35]
The GB photo app always shows the last photo (so if you have 1 photo, it will be the first , if you have 3 photos it will be the 3rd) as deleted. At least, I assume that is what the little "D" in the top corner means. Seems like there may be an off by one issue somewhere.

**Comment by EstebanFuentealba** [comment]
Yep, the letter "D" refers to a deleted image. Could you share your .sav file to test the app? I assume that starting tomorrow, there will be several apps with various [fixes available in the official catalog](https://github.com/flipperdevices/flipper-application-catalog/pull/331) again.

Do you have the `Game Boy Camera` or `Pocket Camera`?

**Comment by nortakales** [comment]
This is all using the latest OFW release (0.100.3) and the latest FAPs from the store (2.2). Save file is zipped since GitHub wouldn't allow `.sav`. Video shows taking a fresh photo (3rd photo in the save file), and then the Flipper gives it the little "D". The cartridge itself is the US model Game Boy Camera.

https://photos.app.goo.gl/v2Yfq3QcHZPJQKsk6

[GAMEBOYCAMERA_0.zip](https://github.com/EstebanFuentealba/MALVEKE-Flipper-Zero/files/14892495/GAMEBOYCAMERA_0.zip)

**Comment by EstebanFuentealba** [comment]
@nortakales  Can you test those fap (GAME BOY CAMERA [MALVEKE-Flipper-Zero-f7-api-60.4-0.100.3](https://github.com/EstebanFuentealba/MALVEKE-Flipper-Zero/actions/runs/8609392913/artifacts/1396278586)) before publishing?

https://github.com/EstebanFuentealba/MALVEKE-Flipper-Zero/actions/runs/8609392913#artifacts

**Comment by nortakales** [comment]
I've tried 6 or 7 times now to pull a save file from my camera and view it in the new fap, but every time the photos come back as just pure static and the save file is gone when I put the camera back in my Game Boy. Sometimes the GB Cartridge app just freezes on "Loading..." when selecting "Cartridge Information" too until I reset the Flipper. I don't know what is going on tonight, but nothing is working. I'm on vacation now so don't have much time but I will keep trying.

**Comment by nortakales** [comment]
As far as I can tell, this new GB Cartridge fap you linked above is not able to pull save files at all. I am having 0% success rate, and my save is wiped 100% of the time.

So I switched back to the GB Cartridge v2.2 fap available in the Flipper app store, kept the GB Photo fap you linked above, and it is still showing "D" for the very last photo.

**Comment by EstebanFuentealba** [comment]
Fixed: Closes with https://github.com/EstebanFuentealba/MALVEKE-Flipper-Zero/commit/2ef8402bbd4f43e4d5609be650a020b7145749fe
